all:
	gcc interpret.c -o interpret
	gcc src/maxnum.c -o maxnum
	gcc src/maxstr.c -o maxstr
	gcc src/strplus.c -o strplus
	gcc src/sum.c -o sum
clean:
	rm -f interpret
	rm -f maxnum
	rm -f maxstr
	rm -f strplus
	rm -f sum